**Table of contents**<a id='toc0_'></a>    
- [Array construction routines](#toc1_)    
- [Random number generation and Sampling with NumPy](#toc2_)    
  - [<u>Simple random sampling</u>](#toc2_1_)    
  - [<u>Setting a <b>seed</b> for reproducibility</u>](#toc2_2_)    
  - [<u>Sampling from particular distributions</u>](#toc2_3_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=2
	maxLevel=4
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

<u>Note:</u> to see the documentation of a function we can use, help(fun_name). Another interesting way to do this in a jupyter notebook is, using the `?` sign followed by the fun_name. 

In [1]:
# Import statements
import numpy as np

## <a id='toc1_'></a>[Array construction routines](#toc0_)

NumPy provides some simple built-in functions to initialize some of the most common arrays used in scientific computing.

- **Array of zeros**

In [2]:
# np.zeros(ary_shape, dtype=float)
zeros_ary = np.zeros((2, 3))

In [3]:
zeros_ary

array([[0., 0., 0.],
       [0., 0., 0.]])

If we want to initialize an array that has the **same shape and dataype** as `a` we can use the `np.zeros_like(a, dtype=float)` function.

- **Array of ones**

In [4]:
# np.ones(ary_shape, dtype=float)
ones_ary = np.ones((2, 3))

In [5]:
ones_ary

array([[1., 1., 1.],
       [1., 1., 1.]])

A function `np.ones_like(a, dtype=float)` is available in case we want an array of the same shape and size as `a`.

- **Array of X**s

In [6]:
# np.full(shape, fill_value, dtype=None)
filled_ary = np.full((2, 3), 3)

In [7]:
filled_ary

array([[3, 3, 3],
       [3, 3, 3]])

Function `np.full_like(a, fill_value, dtype=None)` will return a full array with the same shape and type as a given array, `a`.

- **The arange function**

In [8]:
# np.arange(start, stop, step, dtype=None)
# stop is exclusive
arange_ary = np.arange(1, 10)

This will return an **one-dimensional** array populated with the numbers in the given range. Similar to python lists but it returns ndarray objects instead.

In [9]:
arange_ary

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- **The linspace function**

In [10]:
# np.linspace(start, stop, num=50, dtype=None)
# stop is inclusive
lin_ary = np.linspace(1, 10, 5, dtype=np.int16)

This will return an **one-dimensional** array of size 'num' and the elements are linearly spaced within the given range.

In [11]:
lin_ary

array([ 1,  3,  5,  7, 10], dtype=int16)

- **Diagonal matrix** from array like structures

A diagonal matrix is a square matrix in which the elements are all zero except the main diagonal entries.

In [12]:
# np.diag(array_like, k=0)
# k : int, optional. Diagonal in question. The default is 0 i.e, the main diagonal.
# Use `k>0` for diagonals above the main diagonal, and `k<0` for diagonals below the main diagonal.
diag_ary = np.diag([1, 2, 3])

In [13]:
diag_ary

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

To extract the diagonal elements of a square matrix, the `np.diag(array, k=0)` fuction can be used.

In [14]:
diag_elm = np.diag(diag_ary)

In [15]:
diag_elm

array([1, 2, 3])

- **Diagonal matrix with 1s along the diagonal and 0s elsewhere**

In [16]:
# np.eye(N, M=None, k=0)
# N is the no of rows in the output matrix and M is the no columns. If, M=None it defaults to N
eye_ary = np.eye(3, 4, k=-1)

In [17]:
eye_ary

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

- **Identity matrix**

The identity matrix is a square matrix with ones on the main diagonal and zeros elsewhere.

In [18]:
# np.identity(n, dtype=None)
iden_ary = np.identity(3)

In [19]:
iden_ary

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## <a id='toc2_'></a>[Random number generation and Sampling with NumPy](#toc0_)

In machine learning and deep learning we often need to generate arrays of random numbers. These types of random arrays can be easily generated with Numpy. Also, for statistical applications, we often need random samples of numbers from various types of statistical distributions. Numpy provides a convenient way to generate and sample data for a wide range of statistical distributions.

Numpy actually generates pseudo-random numbers. But, for all practical purposes it is random enough to be considered truly random. 

Numpy provides a subpackage named `random` for working with random numbers and distributions. Previously, `random.random` class was used. But, starting from V1.17.0 it recommends users to use the `Generator` approach. To learn more about this approach and available functions see - https://numpy.org/devdocs/reference/random/generator.html 

- **Initializing the Random Generator object**

In [20]:
from numpy.random import default_rng

rng = default_rng()

### <a id='toc2_1_'></a>[<u>Simple random sampling</u>](#toc0_)

- **An array of random integers**

`rng.integers(low, high=None, size=None, dtype=np.int64)` will return an array of specified shape populated with random integers from low (inclusive) to high (exclusive).

In [21]:
randint_ary = rng.integers(
    [1, 4, 2], [10, 8, 7], size=(3, 3)
)  # col1:(low=1, high=10), col2:(low=4, high=8);col3:(low=2, high=7)

In [22]:
randint_ary

array([[2, 5, 3],
       [5, 7, 4],
       [9, 6, 3]])

- **An array of random floats in the half-open interval [0.0, 1.0)**

`rng.random(size=None, dtype=np.float64, out=None)` will return an array of specified shape populated by random floats from the "continuous uniform" distribution over the stated interval.

In [23]:
rand_ary = rng.random(size=(2, 3, 3))

In [24]:
rand_ary

array([[[0.54262496, 0.97407784, 0.22273485],
        [0.64211916, 0.34748703, 0.06535791],
        [0.97039635, 0.22035921, 0.45719539]],

       [[0.47590258, 0.64791843, 0.55870738],
        [0.94452409, 0.96002789, 0.50087617],
        [0.45096658, 0.94155353, 0.18163461]]])

- **To generate a random sample from a given array**

`rng.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)` will generate a random sample of specified shape populated with the elements from a given array `a`

In [25]:
rand_sample = rng.choice(randint_ary, size=(2, 2))

In [26]:
rand_sample

array([[[9, 6, 3],
        [5, 7, 4]],

       [[5, 7, 4],
        [2, 5, 3]]])

### <a id='toc2_2_'></a>[<u>Setting a <b>seed</b> for reproducibility</u>](#toc0_)

In [27]:
# setting a seed and producing a random array

In [28]:
rng_seeded = default_rng(seed=285)

rnd_sd_int = rng_seeded.integers(low=6, size=3)  # effectively: low=0, high=6

In [29]:
# see, if using the previously used seed produces the same output

In [30]:
rng_seeded_rpcd = default_rng(seed=285)

rnd_sd_int_rpcd = rng_seeded_rpcd.integers(low=6, size=3)

In [31]:
print(rnd_sd_int == rnd_sd_int_rpcd)

[ True  True  True]


### <a id='toc2_3_'></a>[<u>Sampling from particular distributions</u>](#toc0_)

See the docs @ https://numpy.org/doc/stable/reference/random/generator.html#distributions