**Table of contents**<a id='toc0_'></a>    
- [Array construction routines](#toc1_)    
- [Adding and removing elements](#toc2_)    
  - [Remove elements](#toc2_1_)    
  - [Append elements](#toc2_2_)    
  - [Insert elements](#toc2_3_)    
- [Random number generation and Sampling with NumPy](#toc3_)    
  - [<u>Simple random sampling</u>](#toc3_1_)    
  - [<u>Setting a <b>seed</b> for reproducibility</u>](#toc3_2_)    
  - [<u>Sampling from particular distributions</u>](#toc3_3_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=2
	maxLevel=4
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [2]:
# Import statements
import numpy as np

## <a id='toc1_'></a>[Array construction routines](#toc0_)

NumPy provides some simple built-in functions to initialize some of the most common arrays used in scientific computing.

- **Array of zeros**

In [3]:
# np.zeros(ary_shape, dtype=float)
zeros_ary = np.zeros((2, 3))

In [4]:
zeros_ary

array([[0., 0., 0.],
       [0., 0., 0.]])

If we want to initialize an array that has the **same shape and dataype** as `a` we can use the `np.zeros_like(a, dtype=float)` function.

- **Array of ones**

In [5]:
# np.ones(ary_shape, dtype=float)
ones_ary = np.ones((2, 3))

In [6]:
ones_ary

array([[1., 1., 1.],
       [1., 1., 1.]])

A function `np.ones_like(a, dtype=float)` is available in case we want an array of the same shape and size as `a`.

- **Array of X**s

In [7]:
# np.full(shape, fill_value, dtype=None)
filled_ary = np.full((2, 3), 3)

In [8]:
filled_ary

array([[3, 3, 3],
       [3, 3, 3]])

Function `np.full_like(a, fill_value, dtype=None)` will return a full array with the same shape and type as a given array, `a`.

- **The arange function**

In [9]:
# np.arange(start, stop, step, dtype=None)
# stop is exclusive
arange_ary = np.arange(1, 10)

This will return an **one-dimensional** array populated with the numbers in the given range. Similar to python lists but it returns ndarray objects instead.

In [10]:
arange_ary

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- **The linspace function**

In [11]:
# np.linspace(start, stop, num=50, dtype=None)
# stop is inclusive
lin_ary = np.linspace(1, 10, 5, dtype=np.int16)

This will return an **one-dimensional** array of size 'num' and the elements are linearly spaced within the given range.

In [12]:
lin_ary

array([ 1,  3,  5,  7, 10], dtype=int16)

- **Diagonal matrix** from array like structures

A diagonal matrix is a square matrix in which the elements are all zero except the main diagonal entries.

In [13]:
# np.diag(array_like, k=0)
# k : int, optional. Diagonal in question. The default is 0 i.e, the main diagonal.
# Use `k>0` for diagonals above the main diagonal, and `k<0` for diagonals below the main diagonal.
diag_ary = np.diag([1, 2, 3])

In [14]:
diag_ary

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

To extract the diagonal elements of a square matrix, the `np.diag(array, k=0)` fuction can be used.

In [15]:
diag_elm = np.diag(diag_ary)

In [16]:
diag_elm

array([1, 2, 3])

- **Diagonal matrix with 1s along the diagonal and 0s elsewhere**

In [17]:
# np.eye(N, M=None, k=0)
# N is the no of rows in the output matrix and M is the no columns. If, M=None it defaults to N
eye_ary = np.eye(3, 4, k=-1)

In [18]:
eye_ary

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

- **Identity matrix**

The identity matrix is a square matrix with ones on the main diagonal and zeros elsewhere.

In [19]:
# np.identity(n, dtype=None)
iden_ary = np.identity(3)

In [20]:
iden_ary

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## <a id='toc2_'></a>[Adding and removing elements](#toc0_)

In [21]:
ary = np.linspace(0, 11, 12).reshape(4, 3)

In [22]:
ary

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

### <a id='toc2_1_'></a>[Remove elements](#toc0_)

In [23]:
# numpy.delete(ary, indices, axis=None)
# indices: object that defines indices of sub-arrays to remove along the specified axis
# axis=None: flattened

# removing first 2 rows
np.delete(ary, range(0, 2), axis=0)  # doesn't change in place.

array([[ 6.,  7.,  8.],
       [ 9., 10., 11.]])

### <a id='toc2_2_'></a>[Append elements](#toc0_)

In [24]:
# numpy.append(ary, values, axis=None)
# doesn't change in place

In [25]:
np.append(ary, [[12, 13, 14]], axis=0)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

### <a id='toc2_3_'></a>[Insert elements](#toc0_)

In [26]:
# numpy.insert(ary, obj_indices, values, axis=None)
# obj_indices: object that defines the index or indices before which values is inserted
# axis=None: array is flattened
# adding three new columns of values [10, 40, 70, 100], [20, 50, 80, 110] and [30, 60, 90, 120]
# at indexes of [0, 1, 3] respectively
# the elements at the same indexes of the supplied iterables are zipped together and forms the
# values of the a column at the respective positions.
np.insert(
    ary, [0, 1, 3], ([10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]), axis=1
)

array([[ 10.,   0.,  20.,   1.,   2.,  30.],
       [ 40.,   3.,  50.,   4.,   5.,  60.],
       [ 70.,   6.,  80.,   7.,   8.,  90.],
       [100.,   9., 110.,  10.,  11., 120.]])

In [27]:
np.insert(
    ary, [0, 1, 3], ([10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]), axis=1
)

array([[ 10.,   0.,  20.,   1.,   2.,  30.],
       [ 40.,   3.,  50.,   4.,   5.,  60.],
       [ 70.,   6.,  80.,   7.,   8.,  90.],
       [100.,   9., 110.,  10.,  11., 120.]])

In [28]:
np.insert(ary, [0, 1, 3], ([10, 20, 30], [40, 50, 60], [70, 80, 90]), axis=0)

array([[10., 20., 30.],
       [ 0.,  1.,  2.],
       [40., 50., 60.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [70., 80., 90.],
       [ 9., 10., 11.]])

## <a id='toc3_'></a>[Random number generation and Sampling with NumPy](#toc0_)

In machine learning and deep learning we often need to generate arrays of random numbers. These types of random arrays can be easily generated with Numpy. Also, for statistical applications, we often need random samples of numbers from various types of statistical distributions. Numpy provides a convenient way to generate and sample data for a wide range of statistical distributions.

Numpy actually generates pseudo-random numbers. But, for all practical purposes it is random enough to be considered truly random. 

Numpy provides a subpackage named `random` for working with random numbers and distributions. Previously, `random.random` class was used. But, starting from V1.17.0 it recommends users to use the `Generator` approach. To learn more about this approach and available functions see - https://numpy.org/devdocs/reference/random/generator.html 

- **Initializing the Random Generator object**

In [29]:
from numpy.random import default_rng

rng = default_rng()

### <a id='toc3_1_'></a>[<u>Simple random sampling</u>](#toc0_)

- **An array of random integers**

`rng.integers(low, high=None, size=None, dtype=np.int64)` will return an array of specified shape populated with random integers from low (inclusive) to high (exclusive).

In [30]:
randint_ary = rng.integers(
    [1, 4, 2], [10, 8, 7], size=(3, 3)
)  # col1:(low=1, high=10), col2:(low=4, high=8);col3:(low=2, high=7)

In [31]:
randint_ary

array([[7, 4, 5],
       [3, 7, 3],
       [3, 4, 4]])

- **An array of random floats in the half-open interval [0.0, 1.0)**

`rng.random(size=None, dtype=np.float64, out=None)` will return an array of specified shape populated by random floats from the "continuous uniform" distribution over the stated interval.

In [32]:
rand_ary = rng.random(size=(2, 3, 3))

In [33]:
rand_ary

array([[[0.69571748, 0.86765106, 0.80572037],
        [0.92826226, 0.47724582, 0.98619143],
        [0.14454529, 0.06686911, 0.75215488]],

       [[0.86469918, 0.88113612, 0.17056614],
        [0.92144948, 0.4615142 , 0.49055468],
        [0.85380644, 0.73827278, 0.34121622]]])

- **An array of random floats in the half-open interval [low, high)**

`rng.uniform(low, high, size)` will return an array of specified shape populated by random floats from the "continuous uniform" distribution over the stated interval.

In [34]:
rand_ary = rng.uniform(-10, 10, size=10)

In [35]:
rand_ary

array([ 6.67416594,  8.00010241, -5.89248779,  8.32010993,  4.34166004,
       -8.92178949, -0.47009184,  7.16270486, -8.17228491,  8.44818023])

- **To generate a random sample from a given array we can use,** `rng.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)`

This will generate a random sample. If the given shape is, e.g., ``(m, n, k)``, then ``(m * n * k)`` samples are drawn from the 1-d `a`. If `a` has more than one dimension, the `size` shape will be inserted into the `axis` dimension, so the output ``ndim`` will be ``a.ndim - 1 + len(size)``.

In [33]:
rand_sample = rng.choice(
    [[8, 5, 4, 3], [1, 8, 6, 4], [3, 5, 6, 9], [0, 8, 7, 2]], size=3
)

In [34]:
rand_sample

array([[1, 8, 6, 4],
       [0, 8, 7, 2],
       [0, 8, 7, 2]])

In [35]:
rand_sample.shape

(3, 4)

In [36]:
rand_sample_1 = rng.choice(
    [[8, 5, 4, 3], [1, 8, 6, 4], [3, 5, 6, 9], [0, 8, 7, 2]], size=(2, 2)
)

In [37]:
rand_sample_1

array([[[3, 5, 6, 9],
        [8, 5, 4, 3]],

       [[8, 5, 4, 3],
        [8, 5, 4, 3]]])

In [38]:
rand_sample_1.shape

(2, 2, 4)

### <a id='toc3_2_'></a>[<u>Setting a <b>seed</b> for reproducibility</u>](#toc0_)

In [39]:
# setting a seed and producing a random array

In [40]:
rng_seeded = default_rng(seed=285)

rnd_sd_int = rng_seeded.integers(low=6, size=3)  # effectively: low=0, high=6

In [41]:
# see, if using the previously used seed produces the same output

In [42]:
rng_seeded_rpcd = default_rng(seed=285)

rnd_sd_int_rpcd = rng_seeded_rpcd.integers(low=6, size=3)

In [43]:
print(rnd_sd_int == rnd_sd_int_rpcd)

[ True  True  True]


### <a id='toc3_3_'></a>[<u>Sampling from particular distributions</u>](#toc0_)

See the docs @ https://numpy.org/doc/stable/reference/random/generator.html#distributions