In [1]:
# import statements
import numpy as np
from numpy.random import default_rng

In [2]:
# random example array
rng = default_rng()
ary = rng.integers(low=5, high=20, size=(4, 3))

# Array Manipulation 

## <u>Shape manipulation 

### Reshaping an Array

In [3]:
# np.reshape(a, newshape)
# Gives a new shape to the array "a" without changing its data.
# doesn't change in-place
np.reshape(ary, (2, 6))

array([[17, 15,  9, 12, 14,  6],
       [19, 15, 11, 19, 11,  8]])

In [4]:
ary

array([[17, 15,  9],
       [12, 14,  6],
       [19, 15, 11],
       [19, 11,  8]])

### Flattening an array

In [5]:
# flatten() will return a copy of the original array
ary.flatten()

array([17, 15,  9, 12, 14,  6, 19, 15, 11, 19, 11,  8])

In [6]:
# ravel() will show only a manipulated view
ary.ravel()

array([17, 15,  9, 12, 14,  6, 19, 15, 11, 19, 11,  8])

## <u>Transpose of an Array

`-->` If an 'n' dimensional array has a shape of <i><b>(i[0], i[1], ... i[n-2], i[n-1])</b></i> , its transpose will have the shape of <i><b>(i[n-1], i[n-2], ... i[1], i[0])</b>. 

- For a 1-D array this has no effect, as a transposed vector is simply the same vector. 
- For a 2-D array, this is a standard matrix transpose.


`-->` To find the transpose of an array we can use the <i>`numpy.transpose(a, axes=None)`</i>. This will Return a view of the array with axes transposed.

- axes=None: reverses the order of the axes

- axes=tuple of ints: a tuple of (i, j) means that, the i-th axis of 'a' will become the j-th axis of the transpose array

In [7]:
ary

array([[17, 15,  9],
       [12, 14,  6],
       [19, 15, 11],
       [19, 11,  8]])

In [8]:
np.transpose(ary)  # or simply, ary.transpose()

array([[17, 12, 19, 19],
       [15, 14, 15, 11],
       [ 9,  6, 11,  8]])

## <u>Working with array dimensions 

Some array operations such as, combining or joining two or more arrays or, mathematical operations, sometimes will not work at all or will work in an unexpected way in case of dimesion mismatch. This is why manipulating array dimensions is a very important operation. 

In [9]:
# example array
a = np.arange(1, 10).reshape(3, 3)

### Expanding

In [10]:
# Expand the shape of an array by inserting a new axis that will appear at the `axis` position in the expanded array shape.
exp_a = np.expand_dims(a, axis=1)

In [11]:
exp_a

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [12]:
exp_a.shape

(3, 1, 3)

### Squeezing

In [13]:
# np.squeeze(x, axis=None)
# the opposite of expanding
# Removes all the axes of length one from `a`
# axis=x will remove only that particular axis but, it must have a length of 1
np.squeeze(exp_a, axis=1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## <u>Broadcasting 

Broadcasting is a mechanism that automatically matches arrays with different shapes (by temporarily converting one to match the other). This is done mainly for element-wise operations. Broadcasting usually improves speed by means of vectorizing operations.

Not all arrays can be broadcast. They must meet certain conditions, the “Broadcasting rule” states: “In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.”

In [14]:
a = np.arange(1, 5).reshape(2, 2)
c = 5
b = np.arange(6, 9).reshape(3, 1)

- Example of Valid broadcasting

In [15]:
a + c

array([[6, 7],
       [8, 9]])

- Example of Invalid broadcasting

In [16]:
try:
    a + b
except ValueError as err_msg:
    print(err_msg)

operands could not be broadcast together with shapes (2,2) (3,1) 
