In [1]:
# import statements
import numpy as np
from numpy.random import default_rng

In [2]:
# random example array
rng = default_rng()
ary = rng.integers(low=5, high=20, size=(4, 3))

# Array Manipulation 

## <u>Shape manipulation 

### Reshaping an Array

In [3]:
# np.reshape(a, newshape)
# Gives a new shape to the array "a" without changing its data.
# doesn't change in-place
np.reshape(ary, (2, 6))

array([[ 9,  8, 17,  6, 15, 12],
       [17, 16, 13, 10,  9, 13]])

In [4]:
ary

array([[ 9,  8, 17],
       [ 6, 15, 12],
       [17, 16, 13],
       [10,  9, 13]])

### Flattening an array

In [5]:
# flatten() will return a copy of the original array
ary.flatten()

array([ 9,  8, 17,  6, 15, 12, 17, 16, 13, 10,  9, 13])

In [6]:
# ravel() will show only a manipulated view
ary.ravel()

array([ 9,  8, 17,  6, 15, 12, 17, 16, 13, 10,  9, 13])

## <u>Transpose of an Array

`-->` If an 'n' dimensional array has a shape of <i><b>(i[0], i[1], ... i[n-2], i[n-1])</b></i> , its transpose will have the shape of <i><b>(i[n-1], i[n-2], ... i[1], i[0])</b>. 

- For a 1-D array this has no effect, as a transposed vector is simply the same vector. 
- For a 2-D array, this is a standard matrix transpose.


`-->` To find the transpose of an array we can use the <i>`numpy.transpose(a, axes=None)`</i>. This will Return a view of the array with axes transposed.

- axes=None: reverses the order of the axes

- axes=tuple of ints: a tuple of (i, j) means that, the i-th axis of 'a' will become the j-th axis of the transpose array

In [7]:
ary

array([[ 9,  8, 17],
       [ 6, 15, 12],
       [17, 16, 13],
       [10,  9, 13]])

In [8]:
np.transpose(ary)  # or simply, ary.transpose()

array([[ 9,  6, 17, 10],
       [ 8, 15, 16,  9],
       [17, 12, 13, 13]])

## <u>Working with array dimensions 

Some array operations such as, combining or joining two or more arrays or, mathematical operations, sometimes will not work at all or will work in an unexpected way in case of dimesion mismatch. This is why manipulating array dimensions is a very important operation. 

In [9]:
# example array
a = np.arange(1, 10).reshape(3, 3)

### Expanding

In [10]:
# Expand the shape of an array by inserting a new axis that will appear at the `axis` position in the expanded array shape.
exp_a = np.expand_dims(a, axis=1)

In [11]:
exp_a

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [12]:
exp_a.shape

(3, 1, 3)

### Squeezing

In [13]:
# np.squeeze(x, axis=None)
# the opposite of expanding
# Removes all the axes of length one from `a`
# axis=x will remove only that particular axis but, it must have a length of 1
np.squeeze(exp_a, axis=1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## <u>Broadcasting 

Broadcasting is a mechanism that automatically matches arrays with different shapes (by temporarily converting one to match the other). This is done mainly for element-wise operations. Broadcasting usually improves speed by means of vectorizing operations.

Not all arrays can be broadcast. They must meet certain conditions, the “Broadcasting rule” states: “In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.”

In [14]:
a = np.arange(1, 5).reshape(2, 2)
c = 5
b = np.arange(6, 9).reshape(3, 1)

- **Example of Valid broadcasting**

In [15]:
a + c

array([[6, 7],
       [8, 9]])

- **Example of Invalid broadcasting**

In [16]:
try:
    a + b
except ValueError as err_msg:
    print(err_msg)

operands could not be broadcast together with shapes (2,2) (3,1) 


## <u> Joining Arrays 

### Concatenation 

To concatenate, the arrays must have equal length along the axis of concatenation.

In [17]:
# example arrays
con_ary1 = np.linspace(1, 9, 9).reshape(3, 3)
con_ary2 = np.linspace(10, 12, 3).reshape(1, 3)

`np.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")`

In [18]:
# Row wise concatenation (to concatenate along axis=0, axix=1 must be equal in all of the arrays to be concatenated)
np.concatenate((con_ary1, con_ary2), axis=0)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [19]:
# Column wise concatenation (to concatenate along axis=1, axis=0 must be equal in all of the arrays to be concatenated)
np.concatenate((con_ary1, con_ary2.T), axis=1)

array([[ 1.,  2.,  3., 10.],
       [ 4.,  5.,  6., 11.],
       [ 7.,  8.,  9., 12.]])

### Stacking 

To stack arrays together, all the arrays must have the same dimensions. And this will add a new dimension to the stacked array. 

We use the `numpy.stack((tuple of arrays), axis=0)` function to perform the stacking operation. The axis parameter specifies the index of the new axis in the dimensions of the result.

In [20]:
stk_ary1 = np.linspace(1, 9, 9).reshape(1, 3, 3)
stk_ary2 = np.linspace(10, 19, 9).reshape(1, 3, 3)

In [21]:
np.stack((stk_ary1, stk_ary2), axis=2).shape

(1, 3, 2, 3)

### Horizontal (column-wise) stacking 

This works differently than simple stacking. `np.hstack()` will add the arrays in a column wise fashion i.e, similar to concatenating along axis=1.

In [22]:
# example arrays
hstk_ary1 = np.linspace(1, 9, 9).reshape(3, 3)
hstk_ary2 = np.linspace(10, 12, 3).reshape(1, 3)

In [23]:
np.hstack((hstk_ary1, hstk_ary2.T))

array([[ 1.,  2.,  3., 10.],
       [ 4.,  5.,  6., 11.],
       [ 7.,  8.,  9., 12.]])

### Vertical (row-wise) stacking 

`np.vstack()` will add the arrays in a row wise fashion i.e, similar to concatenating along axis=0.

In [24]:
# example arrays
vstk_ary1 = np.linspace(1, 9, 9).reshape(3, 3)
vstk_ary2 = np.linspace(10, 12, 3).reshape(1, 3)

In [25]:
np.vstack((vstk_ary1, vstk_ary2))

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

## <u> Splitting Arrays

In [26]:
# example array
sp_ary = np.linspace(0, 30, 12).reshape(4, 3)

### Splitting an array into multiple sub-arrays of equal length

- **numpy.split(ary, sections, axis=0)**

If the size of the array along the specified axis is not divisible by the number of sections specified, it will throw an error.

In [27]:
np.split(sp_ary, 2)

[array([[ 0.        ,  2.72727273,  5.45454545],
        [ 8.18181818, 10.90909091, 13.63636364]]),
 array([[16.36363636, 19.09090909, 21.81818182],
        [24.54545455, 27.27272727, 30.        ]])]

- **numpy.split_array(ary, sections, axis=0)**

    - If there are more elements in the array along the defined axis after splitting then, extra elements will be discarded.
    - If there are not enough elements in the array along the defined axis then, an empty axis will be generated in some of the splitted arrays.

In [28]:
np.array_split(sp_ary, 4, axis=1)

[array([[ 0.        ],
        [ 8.18181818],
        [16.36363636],
        [24.54545455]]),
 array([[ 2.72727273],
        [10.90909091],
        [19.09090909],
        [27.27272727]]),
 array([[ 5.45454545],
        [13.63636364],
        [21.81818182],
        [30.        ]]),
 array([], shape=(4, 0), dtype=float64)]

### Horizontal (column-wise) splitting 

**Note:** It is a must that, No of sections == No of columns

In [29]:
# numpy.hsplit(ary, sections)
np.hsplit(sp_ary, 3)

[array([[ 0.        ],
        [ 8.18181818],
        [16.36363636],
        [24.54545455]]),
 array([[ 2.72727273],
        [10.90909091],
        [19.09090909],
        [27.27272727]]),
 array([[ 5.45454545],
        [13.63636364],
        [21.81818182],
        [30.        ]])]

### Vertical (row-wise) splitting  

**Note:** It is a must that, No of sections == No of rows

In [30]:
# numpy.vsplit(ary, sections)
np.vsplit(sp_ary, 4)

[array([[0.        , 2.72727273, 5.45454545]]),
 array([[ 8.18181818, 10.90909091, 13.63636364]]),
 array([[16.36363636, 19.09090909, 21.81818182]]),
 array([[24.54545455, 27.27272727, 30.        ]])]

## <u> Array repetition 

In [31]:
# example array
rp_ary = np.linspace(1, 9, 9).reshape(3, 3)

### Repeat an Array a given number of times

In [32]:
# numpy.tile(ary, reps)
np.tile(rp_ary, 2)

array([[1., 2., 3., 1., 2., 3.],
       [4., 5., 6., 4., 5., 6.],
       [7., 8., 9., 7., 8., 9.]])

### Repeat elements of an array 

In [33]:
# numpy.repeat(ary, reps, axis=None)
# axis=None will repeat the array elements in a flattened version of the array
np.repeat(rp_ary, 2, axis=0)

array([[1., 2., 3.],
       [1., 2., 3.],
       [4., 5., 6.],
       [4., 5., 6.],
       [7., 8., 9.],
       [7., 8., 9.]])

## <u> Adding and removing elements 

In [34]:
ary = np.linspace(0, 11, 12).reshape(4, 3)

In [35]:
ary

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

### Remove elements

In [36]:
# numpy.delete(ary, indices, axis=None)
# indices: object that defines indices of sub-arrays to remove along the specified axis
# axis=None: flattened
# removing first 2 rows
np.delete(ary, range(0, 2), axis=0)  # doesn't change in place.

array([[ 6.,  7.,  8.],
       [ 9., 10., 11.]])

### Insert elements

In [37]:
# numpy.insert(ary, obj_indices, values, axis=None)
# obj_indices: object that defines the index or indices before which values is inserted
# axis=None: array is flattened
# adding three new columns of values [10, 20, 30] at indexes of [0, 1, 3] respectively
np.insert(ary, [0, 1, 3], [10, 20, 30], axis=1)

array([[10.,  0., 20.,  1.,  2., 30.],
       [10.,  3., 20.,  4.,  5., 30.],
       [10.,  6., 20.,  7.,  8., 30.],
       [10.,  9., 20., 10., 11., 30.]])