**Table of contents**<a id='toc0_'></a>    
- [Array Indexing and Slicing](#toc1_)    
  - [<u> Simple indexing and slicing </u>](#toc1_1_)    
  - [<u>Boolean indexing or, Masking</u>](#toc1_2_)    
  - [<u>Numpy Indexing Routines</u>](#toc1_3_)    
- [Array Views (Shallow copies) and Deep copies](#toc2_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=2
	maxLevel=4
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

## <a id='toc1_'></a>[Array Indexing and Slicing](#toc0_)

In [2]:
# Import statements
import numpy as np

### <a id='toc1_1_'></a>[<u> Simple indexing and slicing </u>](#toc0_)

Indices represents the position of a particular element in an array. Indexing and slicing in NumPy works similar to Python lists. 

To index arrays with multiple dimensions we need to reference each dimension/axis within a single pair of square brackets with each dimension/axis separated by commas [ , ].

Array slicing operation is also similar to that of Python Lists.

In [3]:
# creating a 3D array to demonstrate array indexing and slicing
ref_3d = np.linspace(1, 30, 30).reshape(
    (2, 3, 5)
)  # 2 stacks in the z axis, 3 rows and 5 columns

In [4]:
ref_3d

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]],

       [[16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.]]])

In [5]:
# extracting the first 2D array from the 2 stacks along the z axis
ref_2d_1 = ref_3d[0]  # same as ref_3d[0, :, :]
# similarly,
ref_2d_2 = ref_3d[1]

In [6]:
ref_2d_1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [7]:
ref_2d_2

array([[16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.]])

<b> <i> Simmilarly, we can extract particular elements or full rows and columns or a specific portion of an array. We can also replace the value of a particular element or any portion of an array using assignment operator `=`. Inserting, deleting, and changing values is done with the same logic. </i> </b>

In [8]:
# for example, changing 23 to 32 in the 3D array
ref_3d[1, 1, 2] = 32  # z - 2nd stack; y - 2nd row; x - 3rd column
ref_3d

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]],

       [[16., 17., 18., 19., 20.],
        [21., 22., 32., 24., 25.],
        [26., 27., 28., 29., 30.]]])

In [9]:
# a 3D array consisting of first 2 rows and 2 columns of the ref_3d array
ref_3d[:, 0:2, 0:2]

array([[[ 1.,  2.],
        [ 6.,  7.]],

       [[16., 17.],
        [21., 22.]]])

-> *Append values at the end of an array*

In [10]:
# inserting a 3rd stack in the z axis
z3_yx_1 = np.linspace(31, 45, 15).reshape(3, 5)
np.append(ref_3d, [z3_yx_1], axis=0)

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]],

       [[16., 17., 18., 19., 20.],
        [21., 22., 32., 24., 25.],
        [26., 27., 28., 29., 30.]],

       [[31., 32., 33., 34., 35.],
        [36., 37., 38., 39., 40.],
        [41., 42., 43., 44., 45.]]])

In [11]:
ref_3d

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]],

       [[16., 17., 18., 19., 20.],
        [21., 22., 32., 24., 25.],
        [26., 27., 28., 29., 30.]]])

### <a id='toc1_2_'></a>[<u>Boolean indexing or, Masking</u>](#toc0_)

An array that has either True or, False as its array elements is known as a boolean array.

In [12]:
# example boolean array
bool_ary = np.array(
    [
        [[True, False, False], [True, True, True]],
        [[False, True, True], [False, False, False]],
    ]
)

In [13]:
bool_ary

array([[[ True, False, False],
        [ True,  True,  True]],

       [[False,  True,  True],
        [False, False, False]]])

Boolean arrays can be used for indexing. This type of indexing is called `masking`. When used, the Boolean array `maps` the elements of that other array corresponding to its `True positions` and `ignores` elements corresponding to the `False positions`.

The only criteria is that, array shapes need to match in at least one of the dimensions. <i>We can index an (n , n) array with an (n, n) mask, a (, n) mask, or an (n, ) mask.</i> Otherwise, it won’t work.

**This type of indexing comes in handy for conditional selection or modification of array elements.**

-> *To extract, only the even elements from ref_3d array --*

In [14]:
# first creating the boolean array i.e, mask (to filter out only the even elements)
mask_even = ref_3d % 2 == 0

In [15]:
mask_even

array([[[False,  True, False,  True, False],
        [ True, False,  True, False,  True],
        [False,  True, False,  True, False]],

       [[ True, False,  True, False,  True],
        [False,  True,  True,  True, False],
        [ True, False,  True, False,  True]]])

In [16]:
mask_even.shape == ref_3d.shape

True

In [17]:
# Now filtering out, only the even elements from ref_3d array
ref_3d[mask_even]

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 32., 24.,
       26., 28., 30.])

<i><b>We can combine multiple logic, comparison, and identity operators to create complex Boolean arrays.</b></i>

-> *To Select elements, (divisible by 3 OR 5) AND (greater than 15) from the ref_3d array --*

In [18]:
mask_req = ((ref_3d % 3 == 0) | (ref_3d % 5 == 0)) & (ref_3d > 15)
ref_3d[mask_req]

array([18., 20., 21., 24., 25., 27., 30.])

-> *To change elements divisible by 3 or 5 to -1 --*

In [19]:
# changes in place

In [20]:
mask_assign = (ref_3d % 3 == 0) | (ref_3d % 5 == 0)
ref_3d[mask_assign] = -1

In [21]:
ref_3d

array([[[ 1.,  2., -1.,  4., -1.],
        [-1.,  7.,  8., -1., -1.],
        [11., -1., 13., 14., -1.]],

       [[16., 17., -1., 19., -1.],
        [-1., 22., 32., -1., -1.],
        [26., -1., 28., 29., -1.]]])

### <a id='toc1_3_'></a>[<u>Numpy Indexing Routines</u>](#toc0_) ([Docs](https://numpy.org/doc/stable/reference/arrays.indexing.html))

Some other useful funcions for indexing arrays that are offered by the NumPy are, `numpy.take`, `numpy.select`, `numpy.choose` etc. For explanations and usage see the documentation.  

#### *Find out the indices of the non-zero elements with `np.nonzero()` --*

In [22]:
ary = np.diag([2, 3, 1])

In [23]:
ary

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 1]])

In [24]:
ary.nonzero()

(array([0, 1, 2]), array([0, 1, 2]))

A common use for nonzero is to find the indices of an array, where a condition is True. Given an array 'a', the condition a > 3 is a boolean array and since False is interpreted as 0, np.nonzero(a > 3) yields the indices of 'a' where the condition is true.

In [25]:
Z = np.arange(10, 19).reshape(3, 3)
np.nonzero(Z>15)

(array([2, 2, 2]), array([0, 1, 2]))

In [26]:
Z[np.nonzero(Z>15)]

array([16, 17, 18])

In [27]:
# equivalent to (This is preffered instead of the previous approach but 
# if you need the indices specifically then use the previous approach)
Z[Z>15]

array([16, 17, 18])

#### *`np.unravel_index(indices, shape)` converts a flat index or array of flat indices into a tuple of coordinate arrays*

- indices: array_like. An integer array whose elements are indices into the flattened version of an array of dimensions 'shape'.
- shape: tuple of ints. The shape of the array to use for unraveling indices.

In [28]:
arr = np.linspace(0, 26, 27).reshape(3, 3, 3)

In [29]:
arr

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

In [30]:
mask = np.unravel_index([1, 3, 5], (3, 3, 3))

In [31]:
mask

(array([0, 0, 0]), array([0, 1, 1]), array([1, 0, 2]))

In [32]:
arr[mask]

array([1., 3., 5.])

#### *Find out the indices to access the main diagonal of an array with arr.ndim >= 2 dimensions and shape (n, n, …, n) using `np.diag_indices(n, ndim=2)`*

In [33]:
arr = np.linspace(1, 30, 36).reshape(4, 3, 3)
print(arr)

[[[ 1.          1.82857143  2.65714286]
  [ 3.48571429  4.31428571  5.14285714]
  [ 5.97142857  6.8         7.62857143]]

 [[ 8.45714286  9.28571429 10.11428571]
  [10.94285714 11.77142857 12.6       ]
  [13.42857143 14.25714286 15.08571429]]

 [[15.91428571 16.74285714 17.57142857]
  [18.4        19.22857143 20.05714286]
  [20.88571429 21.71428571 22.54285714]]

 [[23.37142857 24.2        25.02857143]
  [25.85714286 26.68571429 27.51428571]
  [28.34285714 29.17142857 30.        ]]]


In [34]:
di = np.diag_indices(3, 3)

In [35]:
arr[di]

array([ 1.        , 11.77142857, 22.54285714])

#### *`np.select(condlist, choicelist, default)` returns an array drawn from elements in choicelist, depending on conditions*

<u> Function Parameters</u>

- condlist: list of bool ndarrays. The list of conditions which determine from which array in choicelist the output elements are taken. When multiple conditions are satisfied, the first one encountered in condlist is used.
- choicelist: list of ndarrays. The list of arrays from which the output elements are taken. It has to be of the same length as condlist.
- default: scalar, optional. The element inserted in output when all conditions evaluate to False.

Returns: ndarray. The output at position m is the m-th element of the array in choicelist where the m-th element of the corresponding array in condlist is True.

In [36]:
ary = np.arange(1, 9).reshape(2, 4)

In [37]:
ary

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
np.select([ary <=5, ary > 4], [ary, ary**2])

array([[ 1,  2,  3,  4],
       [ 5, 36, 49, 64]])

#### *`np.where(condition, x, y)` yields 'x' where the condition is True, otherwise yields 'y'*

In [39]:
np.where(ary>5, ary**2, ary)

array([[ 1,  2,  3,  4],
       [ 5, 36, 49, 64]])

## <a id='toc2_'></a>[Array Views (Shallow copies) and Deep copies](#toc0_)

`Views or, Shalow copies:` It is important to note that **previously, conventional indexing and slicing of arrays returned views (or, shallow copies) but this behaviour has changed in current versions.** 

When we use assignment operator (=) to create a copy of the original array a shallow copy is created. The original array and the array that we have copied are the same and also shares the same location in memory. 

This is desirable in some cases since it increases the computational speed and also reduces memory usage. But it also has its cons. Any change in the view array will actually result in changing the original array since both shares the same memory locations.

`Deep Copies:` To truly copy an array i.e, its contents into another array, in different location on the memory than the original one, we should use either the **ndarray.copy()** or, **ndarray.deep_copy()** functions.

- #### *Shallow copy (New label)*

In [22]:
# example array
ary_a = [1, 2, 3]

In [23]:
ary_b = ary_a

In [24]:
print("Check whether ary_a and ary_b has the same elements: ", ary_b is ary_a)
print(
    "Check whether ary_a and ary_b shares the same memory location: ",
    id(ary_a) == id(ary_b),
)

Check whether ary_a and ary_b has the same elements:  True
Check whether ary_a and ary_b shares the same memory location:  True


In [25]:
# modify ary_b
ary_b[0] = 99
ary_b

[99, 2, 3]

In [26]:
# see whether ary_a has also been modified
ary_a

[99, 2, 3]

- #### *Slices no longer returns views*

In [27]:
ary_c = ary_a[0:2]
ary_c

[99, 2]

In [28]:
print("Check whether ary_a and ary_c has the same elements: ", ary_c is ary_a)
print(
    "Check whether ary_a and ary_c shares the same memory location: ",
    id(ary_a) == id(ary_c),
)

Check whether ary_a and ary_c has the same elements:  False
Check whether ary_a and ary_c shares the same memory location:  False


In [29]:
# modify ary_c
ary_c[0] = 20
ary_c

[20, 2]

In [30]:
# see whether ary_a has also been modified
ary_a

[99, 2, 3]

- #### *Deep copy*

In [31]:
ary_d = ary_c.copy()

In [32]:
ary_d

[20, 2]

In [33]:
# modifying ary_d
ary_d[-1] = 18
ary_d

[20, 18]

In [34]:
# see whether ary_c has also been modified
ary_c

[20, 2]