# Array Indexing and Slicing

**Table of contents**<a id='toc0_'></a>    
- [<u> Simple indexing and slicing </u>](#toc1_)    
- [<u>Boolean indexing or, Masking</u>](#toc2_)    
- [<u>Numpy Indexing Routines</u>](#toc3_)    
    - [Shallow copy (New label)](#toc3_1_1_)    
    - [Slices no longer returns views](#toc3_1_2_)    
    - [Deep copy](#toc3_1_3_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=2
	maxLevel=4
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [1]:
# Import statements
import numpy as np

## <a id='toc1_'></a>[<u> Simple indexing and slicing </u>](#toc0_)

Indices represents the position of a particular element in an array. Indexing and slicing in NumPy works similar to Python lists. 

To index arrays with multiple dimensions we need to reference each dimension/axis within a single pair of square brackets with each dimension/axis separated by commas [ , ].

Array slicing operation is also similar to that of Python Lists.

In [2]:
# creating a 3D array to demonstrate array indexing and slicing
ref_3d = np.linspace(1, 30, 30).reshape(
    (2, 3, 5)
)  # 2 stacks in the z axis, 3 rows and 5 columns

In [3]:
ref_3d

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]],

       [[16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.]]])

In [4]:
# extracting the first 2D array from the 2 stacks along the z axis
ref_2d_1 = ref_3d[0]  # same as ref_3d[0, :, :]
# similarly,
ref_2d_2 = ref_3d[1]

In [5]:
ref_2d_1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [6]:
ref_2d_2

array([[16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.]])

<b> <i> Simmilarly, we can extract particular elements or full rows and columns or a specific portion of an array. We can also replace the value of a particular element or any portion of an array using assignment operator `=`. Inserting, deleting, and changing values is done with the same logic. </i> </b>

In [7]:
# for example, changing 23 to 32 in the 3D array
ref_3d[1, 1, 2] = 32  # z - 2nd stack; y - 2nd row; x - 3rd column
ref_3d

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]],

       [[16., 17., 18., 19., 20.],
        [21., 22., 32., 24., 25.],
        [26., 27., 28., 29., 30.]]])

In [8]:
# a 3D array consisting of first 2 rows and 2 columns of the ref_3d array
ref_3d[:, 0:2, 0:2]

array([[[ 1.,  2.],
        [ 6.,  7.]],

       [[16., 17.],
        [21., 22.]]])

- **Append values at the end of an array**

In [9]:
# numpy.append(arr, values, axis=None)
# doesn't change in place

In [10]:
# inserting a 3rd stack in the z axis
z3_yx_1 = np.linspace(31, 45, 15).reshape(3, 5)
np.append(ref_3d, [z3_yx_1], axis=0)

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]],

       [[16., 17., 18., 19., 20.],
        [21., 22., 32., 24., 25.],
        [26., 27., 28., 29., 30.]],

       [[31., 32., 33., 34., 35.],
        [36., 37., 38., 39., 40.],
        [41., 42., 43., 44., 45.]]])

In [11]:
ref_3d

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]],

       [[16., 17., 18., 19., 20.],
        [21., 22., 32., 24., 25.],
        [26., 27., 28., 29., 30.]]])

## <a id='toc2_'></a>[<u>Boolean indexing or, Masking</u>](#toc0_)

An array that has either True or, False as its array elements is known as a boolean array.

In [12]:
# example boolean array
bool_ary = np.array(
    [
        [[True, False, False], [True, True, True]],
        [[False, True, True], [False, False, False]],
    ]
)

In [13]:
bool_ary

array([[[ True, False, False],
        [ True,  True,  True]],

       [[False,  True,  True],
        [False, False, False]]])

Boolean arrays can be used for indexing. This type of indexing is called `masking`. When used, the Boolean array `maps` the elements of that other array corresponding to its `True positions` and `ignores` elements corresponding to the `False positions`.

The only criteria is that, array shapes need to match in at least one of the dimensions. <i>We can index an (n , n) array with an (n, n) mask, a (, n) mask, or an (n, ) mask.</i> Otherwise, it won’t work.

**This type of indexing comes in handy for conditional selection or modification of array elements.**

    - To extract, only the even elements from ref_3d array:

In [14]:
# first creating the boolean array i.e, mask (to filter out only the even elements)
mask_even = ref_3d % 2 == 0

In [15]:
mask_even

array([[[False,  True, False,  True, False],
        [ True, False,  True, False,  True],
        [False,  True, False,  True, False]],

       [[ True, False,  True, False,  True],
        [False,  True,  True,  True, False],
        [ True, False,  True, False,  True]]])

In [16]:
mask_even.shape == ref_3d.shape

True

In [17]:
# Now filtering out, only the even elements from ref_3d array
ref_3d[mask_even]

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 32., 24.,
       26., 28., 30.])

<i><b>We can combine multiple logic, comparison, and identity operators to create complex Boolean arrays.</b></i>

    - To Select elements, (divisible by 3 OR 5) AND (greater than 15) from the ref_3d array:

In [18]:
mask_req = ((ref_3d % 3 == 0) | (ref_3d % 5 == 0)) & (ref_3d > 15)
ref_3d[mask_req]

array([18., 20., 21., 24., 25., 27., 30.])

    - To Change elements divisible by 3 or 5 to -1:

In [19]:
# changes in place

In [20]:
mask_assign = (ref_3d % 3 == 0) | (ref_3d % 5 == 0)
ref_3d[mask_assign] = -1

In [21]:
ref_3d

array([[[ 1.,  2., -1.,  4., -1.],
        [-1.,  7.,  8., -1., -1.],
        [11., -1., 13., 14., -1.]],

       [[16., 17., -1., 19., -1.],
        [-1., 22., 32., -1., -1.],
        [26., -1., 28., 29., -1.]]])

## <a id='toc3_'></a>[<u>Numpy Indexing Routines</u>](#toc0_)

Some other useful funcions for indexing arrays that are offered by the NumPy are, `numpy.take`, `numpy.select`, `numpy.choose` etc. For explanations and usage see the documentation @ https://numpy.org/doc/stable/reference/arrays.indexing.html  

# Array Views (Shallow copies) and Deep copies

`Views or, Shalow copies:` It is important to note that, **previously conventional indexing and slicing of arrays returned views (or, shallow copies) but this behaviour has changed in current versions.** 

The way a shallow copy is created is when we use assignment operator (=) to create a copy of the original array. The original array and the array that we have copied are the same and also shares the same location in memory. As a result the copy array just indicates to the memory location of the main array.  This is desirable in some cases since it increases the computational speed and also reduces memory usage. But it also has its cons. Namely, any change in the view array will actually result in changing the original array since both shares the same memory locations.

`Deep Copies:` To truly copy an array i.e, its contents into another array, in different locations on the memory than the original one, we should use either the **ndarray.copy()** or, **ndarray.deep_copy()** functions.

#### <a id='toc3_1_1_'></a>[Shallow copy (New label)](#toc0_)

In [22]:
# example array
ary_a = [1, 2, 3]

In [23]:
ary_b = ary_a

In [24]:
print("Check whether ary_a and ary_b has the same elements: ", ary_b is ary_a)
print(
    "Check whether ary_a and ary_b shares the same memory location: ",
    id(ary_a) == id(ary_b),
)

Check whether ary_a and ary_b has the same elements:  True
Check whether ary_a and ary_b shares the same memory location:  True


In [25]:
# modify ary_b
ary_b[0] = 99
ary_b

[99, 2, 3]

In [26]:
# see whether ary_a has also been modified
ary_a

[99, 2, 3]

#### <a id='toc3_1_2_'></a>[Slices no longer returns views](#toc0_)

In [27]:
ary_c = ary_a[0:2]
ary_c

[99, 2]

In [28]:
print("Check whether ary_a and ary_c has the same elements: ", ary_c is ary_a)
print(
    "Check whether ary_a and ary_c shares the same memory location: ",
    id(ary_a) == id(ary_c),
)

Check whether ary_a and ary_c has the same elements:  False
Check whether ary_a and ary_c shares the same memory location:  False


In [29]:
# modify ary_c
ary_c[0] = 20
ary_c

[20, 2]

In [30]:
# see whether ary_a has also been modified
ary_a

[99, 2, 3]

#### <a id='toc3_1_3_'></a>[Deep copy](#toc0_)

In [31]:
ary_d = ary_c.copy()

In [32]:
ary_d

[20, 2]

In [33]:
# modifying ary_d
ary_d[-1] = 18
ary_d

[20, 18]

In [34]:
# see whether ary_c has also been modified
ary_c

[20, 2]