# Array Mathematics and Element wise operation

**Table of contents**<a id='toc0_'></a>    
- [<u>NumPy math routines](#toc1_)    
  - [Arithmetic Operations](#toc1_1_)    
  - [Trigonometric and Hyperbolic functions](#toc1_2_)    
  - [Rounding](#toc1_3_)    
  - [Exponential and Logarithmic functions](#toc1_4_)    
  - [Handling Complex numbers](#toc1_5_)    
  - [Some other useful mathematical operations](#toc1_6_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=2
	maxLevel=4
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [2]:
# import statements
import numpy as np

In NumPy, many array operations are element wise. `Element-wise` means, any operation or manipulation of the array affects all the elements of that array and the elements are manipulated separately but, simultaneously. This is where the idea of `Broadcasting` comes in.

## <a id='toc1_'></a>[<u>NumPy math routines](#toc0_)

<b><i>To see all the available NumPy math routines and their usage see @  https://numpy.org/doc/stable/reference/routines.math.html </i></b>

------------
### <a id='toc1_1_'></a>[Arithmetic Operations](#toc0_)
---------------

Array arithmetic operations are element-wise. For example, in case of adding two (3, 3) arrays, the top-left elements in each array are added together, the top-right elements of each array are added together, and so on. Subtraction, division, multiplication, exponentiation, logarithms, roots, and many other algebraic operations will be performed in the same manner.

In [3]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)

In [4]:
# addition
np.add(a, b)  # or, just (a + b)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [5]:
# subtraction
np.subtract(b, a)  # or, just (b - a)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [6]:
# multiplication
np.multiply(a, b)  # or, just (a * b)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [7]:
# power
np.power(b, 2)  # or, just (b ** 2)

array([[100, 121, 144],
       [169, 196, 225],
       [256, 289, 324]])

In [8]:
# division
np.divide(b, a)  # or, just (b / a)

array([[10.        ,  5.5       ,  4.        ],
       [ 3.25      ,  2.8       ,  2.5       ],
       [ 2.28571429,  2.125     ,  2.        ]])

In [9]:
# floor division
np.floor_divide(b, a)  # or, just (b // a)

array([[10,  5,  4],
       [ 3,  2,  2],
       [ 2,  2,  2]])

In [10]:
# remainder
np.remainder(b, a)  # or, just (b % a)

array([[0, 1, 0],
       [1, 4, 3],
       [2, 1, 0]])

In [11]:
# divmod (Return element-wise quotient and remainder simultaneously.)
np.divmod(b, a)  # np.divmod(x, y) is equivalent to (x // y, x % y) but faster

(array([[10,  5,  4],
        [ 3,  2,  2],
        [ 2,  2,  2]]),
 array([[0, 1, 0],
        [1, 4, 3],
        [2, 1, 0]]))

**These operations can as easily be done on complex numbers.**

---------------------
### <a id='toc1_2_'></a>[Trigonometric and Hyperbolic functions](#toc0_)
---------------------

<i><u>See the docs,

Trigonometric functions @ https://numpy.org/doc/stable/reference/routines.math.html#trigonometric-functions

Hyperbolic functions @ https://numpy.org/doc/stable/reference/routines.math.html#hyperbolic-functions

------------------
### <a id='toc1_3_'></a>[Rounding](#toc0_)
-------------------

Rounding is very important in scientific computing as rounding errors, when compounded over large sequences of operations, can produce completely different results. This is a delicate matter since we have to decide between computing power and degree of accuracy of a calculation.

In [12]:
# Array of decimals
ary_r = np.linspace(1, 10, 20).reshape(4, 5)

In [13]:
ary_r

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [14]:
# round to the given number of decimals
np.round(ary_r, 3)  # np.around() produces identical results

array([[ 1.   ,  1.474,  1.947,  2.421,  2.895],
       [ 3.368,  3.842,  4.316,  4.789,  5.263],
       [ 5.737,  6.211,  6.684,  7.158,  7.632],
       [ 8.105,  8.579,  9.053,  9.526, 10.   ]])

In [15]:
# round to the nearest integer
np.rint(ary_r)

array([[ 1.,  1.,  2.,  2.,  3.],
       [ 3.,  4.,  4.,  5.,  5.],
       [ 6.,  6.,  7.,  7.,  8.],
       [ 8.,  9.,  9., 10., 10.]])

In [16]:
# round to the nearest integer towards zero
np.fix(ary_r)

array([[ 1.,  1.,  1.,  2.,  2.],
       [ 3.,  3.,  4.,  4.,  5.],
       [ 5.,  6.,  6.,  7.,  7.],
       [ 8.,  8.,  9.,  9., 10.]])

In [17]:
# round to the floor of the input
np.floor(ary_r)

array([[ 1.,  1.,  1.,  2.,  2.],
       [ 3.,  3.,  4.,  4.,  5.],
       [ 5.,  6.,  6.,  7.,  7.],
       [ 8.,  8.,  9.,  9., 10.]])

In [18]:
# round to the ceiling of the input
np.ceil(ary_r)

array([[ 1.,  2.,  2.,  3.,  3.],
       [ 4.,  4.,  5.,  5.,  6.],
       [ 6.,  7.,  7.,  8.,  8.],
       [ 9.,  9., 10., 10., 10.]])

---------------------
### <a id='toc1_4_'></a>[Exponential and Logarithmic functions](#toc0_)
---------------------

<i>See the docs @ https://numpy.org/doc/stable/reference/routines.math.html#exponents-and-logarithms

--------------------------
### <a id='toc1_5_'></a>[Handling Complex numbers](#toc0_)
---------------------------

In [19]:
# array of complex numbers
cmplx_ary = [[2 - 5j, 4 + 2j], [3 + 2j, 1 + 2j]]

In [20]:
cmplx_ary

[[(2-5j), (4+2j)], [(3+2j), (1+2j)]]

In [21]:
# Angle of the complex argument (by default in, degree)
np.angle(cmplx_ary)

array([[-1.19028995,  0.46364761],
       [ 0.5880026 ,  1.10714872]])

In [22]:
# The real part of a complex argument
np.real(cmplx_ary)

array([[2., 4.],
       [3., 1.]])

In [23]:
# The imaginary part of a complex argument
np.imag(cmplx_ary)

array([[-5.,  2.],
       [ 2.,  2.]])

In [24]:
# The complex conjugate
np.conjugate(cmplx_ary)

array([[2.+5.j, 4.-2.j],
       [3.-2.j, 1.-2.j]])

-------------------------
### <a id='toc1_6_'></a>[Some other useful mathematical operations](#toc0_)
--------------

In [25]:
# square root
np.sqrt(cmplx_ary)

array([[1.92160933-1.30099285j, 2.05817103+0.48586827j],
       [1.81735402+0.55025052j, 1.27201965+0.78615138j]])

In [28]:
print("a:\n", a)
print("b:\n", b)

a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [28]:
# Sum of array elements over a given axis

# If no axis is defined then this will return sum of all the elements in the array.
np.sum(b, axis=0)  # sum along columns (axis=0: y axis; as, 2D array)

array([39, 42, 45])

In [29]:
# Product of array elements over a given axis

# If no axis is defined then this will return product of all the elements in the array.
np.product(a, axis=0)  # product along rows (axis=1: x axis; as, 2D array)

array([ 28,  80, 162])

In [30]:
# Absolute values (element wise)
np.absolute(a - b)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])