In [1]:
# Import statements
import numpy as np

# Logic functions and Array evaluation

Logic functions comes in really handy while slicing and/or, indexing arrays. This is also very useful while performing data transformations.

##  Truth value evaluation (Boolean testing)

Boolean testing refers to checking whether **all** or **some** elements of an array evaluates to true.

In [2]:
# example array
ary_some = np.array([[False, 0, np.nan, 1], [0, np.nan, False, False]])
ary_all = np.ones((3, 4))

- **Test whether all array elements along a given axis evaluate to True**

In [3]:
# check whether all elements of the array, ary_all is True
ary_all.all()

True

In [4]:
# check whether all elements of the array, ary_some is True
ary_some.all()

False

- **Test whether any array elements along a given axis evaluate to True**

In [5]:
# check whether any elements of the array, ary_all is True
ary_all.any()

True

In [6]:
# check whether any elements of the array, ary_some is True along the columns i.e, axis=0
ary_some.any(axis=0)

array([False,  True,  True,  True])

## Array elements testing 

The available testing methods are, `isfinite`, `isinf`, `isnan`, `isnat`, `isneginf`, `isposinf`. To learn in details see the documentation @ https://numpy.org/doc/stable/reference/routines.logic.html#array-contents . 

These functions will always test the array element wise and will return the result as a boolean array.

These functions comes in very handy while cleaning the data and for debugging purposes.

In [7]:
# check not a number
np.isnan(ary_some)

array([[False, False,  True, False],
       [False,  True, False, False]])

## Array elements type testing 

Some available methods are, `isreal`, `iscomplex`, `isscalar` etc. See all the available functions and their documentation @ https://numpy.org/doc/stable/reference/routines.logic.html#array-type-testing .

In [8]:
# example array
ary_cmplx = np.array([[3 + 2j, 2 - 3j, 0], [0 - 1j, 1 + 1j, 2 - 1j]])

In [9]:
# check if array elements are real
np.isreal(ary_cmplx)

array([[False, False,  True],
       [False, False, False]])

In [10]:
# check if array elements are complex
np.iscomplex(ary_cmplx)

array([[ True,  True, False],
       [ True,  True,  True]])

## Logical operations

The available functions are, `logical_or`, `logical_and`, `logical_nor` and `logical_xor`. See the documentation @ https://numpy.org/doc/stable/reference/routines.logic.html#logical-operations . 

All of these methods computes the truth value of (x1 logical_operation x2), element-wise.

## Array comparison 

Some available functions are, `allclose`, `isclose`, `array_equal`, `array_equiv`, `greater`, `less`, `equal` etc. See all the available functions and their documentation @ https://numpy.org/doc/stable/reference/routines.logic.html#comparison .

In [11]:
# example arrays
ary_a = [1e10, 1e-10, 1.00001e10, 1e-8, np.nan]
ary_b = [1e11, 1e-8, 1.01e10, 1e-9, np.nan]
ary_c = [1e10, 1e-8]
ary_d = [1.00001e10, 1e-9]

- **Check if two arrays are equal within a tolerance (element-wise) {return: True or, False}**

In [12]:
np.allclose(ary_c, ary_d)

True

- **Check if two arrays are equal within a tolerance (element-wise) {return: boolean array}**

In [13]:
np.isclose(ary_a, ary_b, equal_nan=True)

array([False,  True, False,  True,  True])