### 100 numpy exercises @ <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
# print(np.__version__)
# print(np.show_config())

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
Z = np.zeros((10))
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
Z = np.ones((10, 10))
print(Z.nbytes)

800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# print(np.info(np.add))

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
Z = np.zeros((10))
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
print(Z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
print(np.arange(0, 9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
Z = np.array([1, 2, 0, 0, 4, 0])
print(Z.nonzero())

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
from numpy.random import default_rng

rng = default_rng()

In [13]:
Z = rng.integers(0, 20, size=(3, 3, 3))
print(Z)

[[[ 7  3  8]
  [17 18 15]
  [13 18  5]]

 [[14 12  0]
  [ 4  9  8]
  [ 0 17  2]]

 [[ 5 14 11]
  [ 0  6  4]
  [14 12  4]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
Z = rng.uniform(2, 20, (10, 10))
print(Z)

[[17.13360964  7.37949828  9.34778232 18.26905551  9.17498783 19.87204885
   8.19818314  6.78867005  4.13019464 18.79976484]
 [ 3.89597989 18.69407616 11.72772167 18.47118927 18.8411022  13.66778167
   9.72502175  3.36044969 19.79453622 16.42675567]
 [16.18878054 13.66346031  9.74732025 18.80812937  8.61500728 11.92257377
   9.92235673  5.63557982 13.34994495 13.1483032 ]
 [13.38340676  7.26975926 10.33089429  3.34935713  4.02528311 16.68977572
   6.55710209 16.3982095   7.74106535  5.13660494]
 [ 7.26664862  6.36314154 13.97808609 18.01544319  5.5472443  13.40806231
  15.88765569  2.24480939 16.23307977 18.511078  ]
 [17.20008616 16.07201548  6.64302876 16.42407998  9.02104468  8.67182581
   7.31911148 15.62781088  7.60775319 12.2797125 ]
 [ 8.78481221  9.98953202 10.12727402 13.68211354  9.92055911 16.9032561
   8.19061286  9.81187018  9.2660371   2.22931402]
 [14.84640546  4.85971065  9.10356892  3.58108333  7.19468139  9.48957456
  19.15093869 17.65994678  5.42564681 11.21797993]
 

In [15]:
print(Z.min())
print(Z.max())

2.2293140223124546
19.952844174906552


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
Z = rng.uniform(-2, 10, 30)
print(Z.mean())

3.846172895315829


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
Z = np.ones((5, 5))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
Z = np.zeros((5, 5))
np.pad(Z, pad_width=1, constant_values=1)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
Z = np.zeros((8, 8))

In [22]:
Z[0::2, 1::2] = 1
Z[1::2, 0::2] = 1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
np.tile(([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

Z-Score Normalization (Standardization): In statistics, this technique involves subtracting the mean of each column from its elements and then dividing by the standard deviation of that column. This centers the distribution of the data around zero with a standard deviation of one.

In [25]:
Z = rng.random((5, 5))
Z = (Z - np.mean(Z)) / np.std(Z)
print(Z)

[[-1.36474396  0.83537176  1.15719567 -0.16356424 -0.63231423]
 [-0.31183098 -1.1730919  -1.3617011  -0.84320882  1.71941003]
 [ 0.80178524 -0.8355513  -0.78281505 -1.11314635  0.52179162]
 [-0.39454481 -0.52523969  1.21162507  0.44922237  1.18927912]
 [ 1.60238434  0.16877492  1.58908424 -0.70526277 -1.0389092 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [26]:
color_dtype = np.dtype(
    [
        ("r", "uint8"),
        ("g", "uint8"),
        ("b", "uint8"),
        ("a", "uint8"),
    ]
)

In [27]:
color_dtype

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
np.matmul((np.linspace(1, 20, 15).reshape(5, 3)), (np.linspace(1, 20, 6).reshape(3, 2)))

array([[ 81.44285714, 108.31428571],
       [186.48571429, 259.77142857],
       [291.52857143, 411.22857143],
       [396.57142857, 562.68571429],
       [501.61428571, 714.14285714]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
Z = rng.integers(0, 9, 10)

In [30]:
Z[(Z > 3) & (Z < 8)] *= -1

In [31]:
print(Z)

[ 0  1 -6 -5 -5  3 -7  8 -6  8]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [32]:
print(sum(range(5), -1))  # -1 is the start value to the sum func
from numpy import *

print(sum(range(5), -1))  # -1 is the axis along which to sum

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [33]:
Z = rng.integers(1, 10, 5)
print(Z)

[4 6 5 4 9]


In [34]:
print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j * Z)
print(Z / 1 / 1)
# print(Z < Z > Z)  # ValueError: The truth value of an array with more than one element is ambiguous.

[      256     46656      3125       256 387420489]
[  8  32  16   8 256]
[False False False False False]
[0.+4.j 0.+6.j 0.+5.j 0.+4.j 0.+9.j]
[4. 6. 5. 4. 9.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [35]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_13621/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_13621/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_13621/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round a float array away from zero? (★☆☆)

In [36]:
Z = rng.uniform(-10, +10, 10)
print(Z)

[ 4.82905126 -2.74727269  4.34565437 -6.30916253  2.83143654  5.81224256
  9.02838627 -4.89675565  7.6667031   6.88191106]


In [37]:
Z = np.where(Z > 0, np.ceil(Z), np.floor(Z))
print(Z)

[ 5. -3.  5. -7.  3.  6. 10. -5.  8.  7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [38]:
Z1 = rng.integers(2, 20, 10)
Z2 = rng.integers(2, 20, 10)

In [39]:
np.intersect1d(Z1, Z2)

array([ 5, 16])

In [40]:
# Z1[np.isclose(Z1, Z2)] is not the solution since it compares the values element wise

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [41]:
# answer(31)
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [42]:
np.sqrt(-1)

/tmp/ipykernel_13621/3438155168.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [43]:
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [44]:
np.datetime64("today") + 1

numpy.datetime64('2023-08-29')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [45]:
np.arange("2016-08", "2016-09", dtype="datetime64[D]")

array(['2016-08-01', '2016-08-02', '2016-08-03', '2016-08-04',
       '2016-08-05', '2016-08-06', '2016-08-07', '2016-08-08',
       '2016-08-09', '2016-08-10', '2016-08-11', '2016-08-12',
       '2016-08-13', '2016-08-14', '2016-08-15', '2016-08-16',
       '2016-08-17', '2016-08-18', '2016-08-19', '2016-08-20',
       '2016-08-21', '2016-08-22', '2016-08-23', '2016-08-24',
       '2016-08-25', '2016-08-26', '2016-08-27', '2016-08-28',
       '2016-08-29', '2016-08-30', '2016-08-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [46]:
A = np.array([2, 3])
B = np.array([4, 5])
((A + B) * (-A / 2))

array([ -6., -12.])

In [47]:
A, B

(array([2, 3]), array([4, 5]))

In [48]:
# answer(35)
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [49]:
Z = rng.uniform(2, 10, (3, 3))

In [50]:
Z

array([[3.48591415, 8.74115945, 9.31724549],
       [2.40761105, 9.1664757 , 6.24827536],
       [7.08162649, 5.47826462, 8.64472042]])

In [51]:
# 1
np.floor(Z)

array([[3., 8., 9.],
       [2., 9., 6.],
       [7., 5., 8.]])

In [52]:
# 2
np.fix(Z)

array([[3., 8., 9.],
       [2., 9., 6.],
       [7., 5., 8.]])

In [53]:
# 3
np.trunc(Z)

array([[3., 8., 9.],
       [2., 9., 6.],
       [7., 5., 8.]])

In [54]:
# 4
Z.astype("int")

array([[3, 8, 9],
       [2, 9, 6],
       [7, 5, 8]])

In [55]:
# 5
Z // 1

array([[3., 8., 9.],
       [2., 9., 6.],
       [7., 5., 8.]])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [56]:
np.tile(np.arange(0, 5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [57]:
# answer(38)
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [58]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [59]:
np.sort(rng.uniform(1, 11, 10))

array([3.39876416, 4.02038137, 5.33909441, 7.31047967, 7.44556543,
       8.14893396, 8.33480373, 8.87468391, 9.45759527, 9.58353046])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [60]:
A = np.linspace(1, 10, 20).reshape(5, 4)
B = np.linspace(1, 10, 20).reshape(5, 4)

In [61]:
(A == B).all()

True

In [62]:
np.array_equal(A, B)

True

In [63]:
np.allclose(A, B)

True

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [64]:
Z = rng.random(10)
print(Z)

[0.90550169 0.84308104 0.91002283 0.13775295 0.26197283 0.56444099
 0.21128334 0.69952657 0.47796327 0.76545834]


In [65]:
Z[Z.argmax()] = 0
print(Z)

[0.90550169 0.84308104 0.         0.13775295 0.26197283 0.56444099
 0.21128334 0.69952657 0.47796327 0.76545834]
