### 100 numpy exercises @ <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
# print(np.__version__)
# print(np.show_config())

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
Z = np.zeros((10))
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
Z = np.ones((10, 10))
print(Z.nbytes)

800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# print(np.info(np.add))

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
Z = np.zeros((10))
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
print(Z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
print(np.arange(0, 9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
Z = np.array([1, 2, 0, 0, 4, 0])
print(Z.nonzero())

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
from numpy.random import default_rng

rng = default_rng()

In [14]:
Z = rng.integers(0, 20, size=(3, 3, 3))
print(Z)

[[[ 5  7 19]
  [17  1 19]
  [11 14  1]]

 [[15  0  1]
  [10 10  1]
  [14  6  9]]

 [[ 2 10  5]
  [ 0  2 12]
  [ 9 12  4]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
Z = rng.uniform(2, 20, (10, 10))
print(Z)

[[ 5.81832    14.27254299 12.76072234 15.76505007 10.928061    6.44950474
   5.54032077  3.92823056 19.90081321  8.72883814]
 [14.75080363 12.48394333  7.9033102  18.55926021  6.95081108  7.80298587
   8.14492544 12.33065762  8.7676383   7.97511377]
 [ 6.19181874 18.57047583  5.62448634 18.02565337 17.83226931  3.28932199
  18.86412601 16.26015589  3.45479914  4.93529206]
 [ 6.64658555  8.13546129 16.66256436 11.00070155  8.87652379  5.76120287
   4.9312832   5.10633475  9.2634331   4.69436772]
 [11.92512833 19.74058439 13.59274393 17.32601385 15.66476602 15.08294151
  19.62674384 10.29667624 18.98900271 16.4113776 ]
 [ 5.88640313  3.94151423  3.35542052 10.26674387 18.71117488  9.28500844
   3.42689671  8.8281273  17.87064107  3.54873425]
 [18.12505527 14.48108002  3.14989523  4.04931989 12.22485544  3.89737133
   2.73194908 14.48075885  4.8876922   8.00438786]
 [13.42660086 18.23260209 17.84578606  7.20023344 11.33155456 10.3088373
   9.85939515 13.24816558 19.62279106  5.16728013]
 

In [16]:
print(Z.min())
print(Z.max())

2.5077137759488846
19.965512922535975


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
Z = rng.uniform(-2, 10, 30)
print(Z.mean())

3.1651562436005887


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
Z = np.ones((5, 5))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
Z = np.zeros((5, 5))
np.pad(Z, pad_width=1, constant_values=1)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
Z = np.zeros((8, 8))

In [23]:
Z[0::2, 1::2] = 1
Z[1::2, 0::2] = 1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [24]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
np.tile(([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

Z-Score Normalization (Standardization): In statistics, this technique involves subtracting the mean of each column from its elements and then dividing by the standard deviation of that column. This centers the distribution of the data around zero with a standard deviation of one.

In [26]:
Z = rng.random((5, 5))
Z = (Z - np.mean(Z)) / np.std(Z)
print(Z)

[[-0.12749802 -1.77907091 -0.42909656  1.29810872 -1.09713265]
 [-0.08218053  1.00172953  0.67062937  0.14769291 -0.7838908 ]
 [ 1.19697321 -0.02743395  1.71467199 -0.95029447 -0.50315815]
 [-0.24239584  0.79071934  1.12748444 -1.47234852 -0.39185366]
 [ 0.94720968 -0.65967209 -0.25992811  1.60448314 -1.69374806]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
color_dtype = np.dtype(
    [
        ("r", "uint8"),
        ("g", "uint8"),
        ("b", "uint8"),
        ("a", "uint8"),
    ]
)

In [28]:
color_dtype

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [29]:
np.matmul((np.linspace(1, 20, 15).reshape(5, 3)), (np.linspace(1, 20, 6).reshape(3, 2)))

array([[ 81.44285714, 108.31428571],
       [186.48571429, 259.77142857],
       [291.52857143, 411.22857143],
       [396.57142857, 562.68571429],
       [501.61428571, 714.14285714]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [30]:
Z = rng.integers(0, 9, 10)

In [31]:
Z[(Z > 3) & (Z < 8)] *= -1

In [32]:
print(Z)

[ 2 -4 -5 -7  2 -4  1  8  1 -6]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [33]:
print(sum(range(5), -1))  # -1 is the start value to the sum func
from numpy import *

print(sum(range(5), -1))  # -1 is the axis along which to sum

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [34]:
Z = rng.integers(1, 10, 5)
print(Z)

[3 1 9 5 1]


In [35]:
print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j * Z)
print(Z / 1 / 1)
# print(Z < Z > Z)  # ValueError: The truth value of an array with more than one element is ambiguous.

[       27         1 387420489      3125         1]
[  4   1 256  16   1]
[False False False False False]
[0.+3.j 0.+1.j 0.+9.j 0.+5.j 0.+1.j]
[3. 1. 9. 5. 1.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [36]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_3016/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_3016/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_3016/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round a float array away from zero? (★☆☆)

In [37]:
Z = rng.uniform(-10, +10, 10)
print(Z)

[-7.04754213  8.10698001  2.42014442 -2.37763702  5.42420924  2.24884239
  0.40321153  6.67693974 -9.80472621  0.68954715]


In [38]:
Z = np.where(Z > 0, np.ceil(Z), np.floor(Z))
print(Z)

[ -8.   9.   3.  -3.   6.   3.   1.   7. -10.   1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [39]:
Z1 = rng.integers(2, 20, 10)
Z2 = rng.integers(2, 20, 10)

In [40]:
np.intersect1d(Z1, Z2)

array([ 2,  6,  7,  8, 15])

In [41]:
# Z1[np.isclose(Z1, Z2)] is not the solution since it compares the values element wise

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [42]:
# answer(31)
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [43]:
np.sqrt(-1)

/tmp/ipykernel_3016/3438155168.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [44]:
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [45]:
np.datetime64("today") + 1

numpy.datetime64('2023-08-30')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [46]:
np.arange("2016-08", "2016-09", dtype="datetime64[D]")

array(['2016-08-01', '2016-08-02', '2016-08-03', '2016-08-04',
       '2016-08-05', '2016-08-06', '2016-08-07', '2016-08-08',
       '2016-08-09', '2016-08-10', '2016-08-11', '2016-08-12',
       '2016-08-13', '2016-08-14', '2016-08-15', '2016-08-16',
       '2016-08-17', '2016-08-18', '2016-08-19', '2016-08-20',
       '2016-08-21', '2016-08-22', '2016-08-23', '2016-08-24',
       '2016-08-25', '2016-08-26', '2016-08-27', '2016-08-28',
       '2016-08-29', '2016-08-30', '2016-08-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [47]:
A = np.array([2, 3])
B = np.array([4, 5])
((A + B) * (-A / 2))

array([ -6., -12.])

In [48]:
A, B

(array([2, 3]), array([4, 5]))

In [49]:
# answer(35)
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [50]:
Z = rng.uniform(2, 10, (3, 3))

In [51]:
Z

array([[4.53239535, 2.2839175 , 2.88440293],
       [6.20530087, 6.0026417 , 3.95624047],
       [5.24807261, 7.09620202, 3.02221809]])

In [52]:
# 1
np.floor(Z)

array([[4., 2., 2.],
       [6., 6., 3.],
       [5., 7., 3.]])

In [53]:
# 2
np.fix(Z)

array([[4., 2., 2.],
       [6., 6., 3.],
       [5., 7., 3.]])

In [54]:
# 3
np.trunc(Z)

array([[4., 2., 2.],
       [6., 6., 3.],
       [5., 7., 3.]])

In [55]:
# 4
Z.astype("int")

array([[4, 2, 2],
       [6, 6, 3],
       [5, 7, 3]])

In [56]:
# 5
Z // 1

array([[4., 2., 2.],
       [6., 6., 3.],
       [5., 7., 3.]])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [57]:
np.tile(np.arange(0, 5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [58]:
# answer(38)
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [59]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [60]:
np.sort(rng.uniform(1, 11, 10))

array([2.55975107, 2.71919162, 3.21580481, 3.32256263, 4.55593427,
       5.60069695, 5.85733026, 8.661991  , 9.20714976, 9.74336376])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [63]:
# answer(41)
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [60]:
A = np.linspace(1, 10, 20).reshape(5, 4)
B = np.linspace(1, 10, 20).reshape(5, 4)

In [61]:
(A == B).all()

True

In [62]:
np.array_equal(A, B)

True

In [63]:
np.allclose(A, B)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [65]:
# answer(43)
Z = np.zeros((3, 3))
Z.flags.writeable = False
try:
    Z[0, 2] = 1
except ValueError as err_msg:
    print(err_msg)

assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

- Radius (r):
    r = √(x² + y²)

- Angle (θ):
    θ = atan2(y, x)

Here, atan2(y, x) is the arctangent function that takes into account the signs of both x and y to determine the correct angle in the appropriate quadrant. 

In [67]:
Z = rng.uniform(2, 10, (10, 2))

In [68]:
Z

array([[2.51276863, 6.30334532],
       [8.64027407, 5.98154969],
       [8.18774768, 9.89426218],
       [7.18258493, 3.85158912],
       [9.04515048, 7.35123756],
       [2.74157258, 7.77817565],
       [5.13967349, 8.16125296],
       [8.67215595, 3.3198447 ],
       [9.26378171, 9.85238239],
       [9.29430928, 3.5915354 ]])

In [69]:
x, y = Z[:, 0], Z[:, 1]

In [70]:
r = np.sqrt((x**2) + (y**2))
print(r)

[ 6.78573271 10.50872365 12.84272698  8.15010828 11.65570422  8.24719568
  9.64480655  9.28588486 13.52357535  9.96410114]


In [71]:
theta = np.arctan2(y, x)  # in radians
theta *= (180/np.pi)  # in degrees
print(theta)

[68.2657724  34.69435331 50.39139879 28.20198799 39.10169055 70.58398124
 57.79870197 20.94767227 46.76362177 21.12768141]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [64]:
Z = rng.random(10)
print(Z)

[0.90550169 0.84308104 0.91002283 0.13775295 0.26197283 0.56444099
 0.21128334 0.69952657 0.47796327 0.76545834]


In [65]:
Z[Z.argmax()] = 0
print(Z)

[0.90550169 0.84308104 0.         0.13775295 0.26197283 0.56444099
 0.21128334 0.69952657 0.47796327 0.76545834]
